import { StyleSheet } from 'react-native';

const styles = StyleSheet.create({
  container: {
    flex: 1,
    justifyContent: 'center',
    backgroundColor: '#FFBF00',
  },
  fundoTab1:{ 
    backgroundColor:'white', 
    borderRadius:30,
    width:'90%',
    flex:1,
    marginVertical:'5%'
  },
  valor:{
    marginTop:'7%',
    fontSize:26,
    alignSelf:'center',
    fontFamily:'AileronH',
  },
  valorAcum:{
    color:'gray',
    fontSize:17,
    alignSelf:'center',
    fontFamily:'AileronR',
  },
  viewBarra:{
    width:'100%', 
    height:'10%', 
    flexDirection:'row', 
    alignSelf:'center',
    marginTop:20,
  },
  barraVerm:{
    backgroundColor:'#FF0000', 
    height:'100%', 
    borderBottomLeftRadius:10, 
    borderTopLeftRadius:10, 
  },
  barraAmarelo:{
    backgroundColor:'#FFBF00', 
    height:'100%', 
  },
  barraCinza:{
    backgroundColor:'#CCCCCC', 
    height:'100%', 
    borderBottomRightRadius:10, 
    borderTopRightRadius:10, 
  },
  viewQuadrados:{
    flexDirection:'row', 
    marginTop:'8%', 
    justifyContent:'space-between',
    paddingHorizontal:'5%'
  },
  quadrVerm:{
    backgroundColor:'#FF0000', 
    width:20, 
    height:20, 
    borderRadius:5,
    justifyContent:'center',
    alignItems:'center'
  },
  quadrAmarelo:{
    backgroundColor:'#FFBF00', 
    width:20, 
    height:20, 
    borderRadius:5,
    justifyContent:'center',
    alignItems:'center'
  },
  quadrCinza:{
    backgroundColor:'#cccccc', 
    width:20, 
    height:20, 
    borderRadius:5,
    justifyContent:'center',
    alignItems:'center'
  },
  viewAtr1:{
    flexDirection:'row', 
    justifyContent:'space-between', 
    padding:25,
    marginBottom:'10%'
  },
  nome:{ 
    marginRight:'5%', 
    fontSize:17,
    fontFamily:'AileronH',
  },
  dataVenc:{
    color:'gray',
    fontSize:15,
    marginTop:'3%',
    fontFamily:'AileronR',
  },
  mes:{
    marginVertical:'5%', 
    fontFamily:'AileronH',
    fontSize:18
  },
  linha:{
    height:'1%', 
    width:'100%', 
    backgroundColor:'#f4f4f4', 
  },
  iconMenu:{
    marginLeft:10,
  },
  numero:{
    color:'white',
    fontFamily:'AileronH',
    fontSize:20
  },
  viewAPA:{
    flexDirection:'row',
    justifyContent:'center',
    paddingVertical:'1%'
  },
  apa:{
    marginVertical:'10%', 
    fontFamily:'AileronR',
    fontSize:18,
    marginHorizontal:40
  },
  apaSelect:{
    fontFamily:'AileronH',
  }
});

export default styles;